### ISSUE TITLE
Search - постраничка bugs

### ISSUE THREAD

**Issue by nataliakozhanova** [AlexPanic/practicum-android-diploma#143]
- если при постраничной загрузке вырубить интернет, не исчезает ProgressBar
- что-то ломается при отображении ошибок при постраничке, например когда удаляем поисковой текст
Действия:
 - С нажатием крестика:
Ввожу поисковой запрос -> получаю несколько страниц резов -> начинаю прокрутку -> выключаю интернет - > ошибка Нет интернета на экране + ProgressBar (BUG) -> нажимаю крестик -> на экране картинка Пустой поиск + ProgressBar (BUG) -> включаю Интернет -> на экране картинка Пустой поиск + ProgressBar (BUG) -> Перехожу на вкладку Избранное и обратно на Серч -> Вижу экран Нет интернета без ProgressBar (BUG) 
- Без нажатия крестика:
Ввожу поисковой запрос -> получаю несколько страниц резов -> начинаю прокрутку -> выключаю интернет - > ошибка Нет интернета на экране + ProgressBar  (BUG) -> включаю Интернет ->  ошибка Нет интернета на экране + ProgressBar (BUG) -> Перехожу на вкладку Избранное и обратно на Серч ->  ошибка Нет интернета на экране (BUG) 

Мысли как должно быть:
- Для постранички нужен Loading не версткой, а функцией типа showPageLoading, а то верстка не знает о стейтах 
- При получении ошибки Нет интернета 2 варианта. Сложный: в корутине пробовать через какое-то время (например 5 сек) перезапустить запрос на получение **той же** страницы, если через 5 сек нет Инета - останавливать все. Простой способ: просто останавливать выполнение. 
- При переходе между фрагментами сохраняется стейт Нет интернета, даже если пользователь удалил текст и ожидает увидеть картинку Пустой поиск (интернет при этом есть).  

Есть ощущение, что при постраничной загрузке нужно поизящнее обрабатывать ошибки и стейты, не так как при обычном поиске.

**Comment by AlexPanic** [comment]
**Условия из задания:**

- Если на устройстве в момент выполнения запроса нет интернета, то отображается соответствующее сообщение об ошибке.
- Если в момент выполнения запроса произошла ошибка, то отображается соответствующее сообщение.
- Если результат поискового запроса пустой, то отображается соответствующее сообщение.
- Если пользователь видит не последнюю страницу результатов поискового запроса, то, когда он пролистывает список вакансий до последнего элемента списка, запрашивается следующая страница контента.
- Успешный запрос одной и той же страницы результатов поискового запроса выполняется только один раз.
- В процессе загрузки новой страницы контента в нижней части экрана отображается индикатор загрузки.
- Вакансии в списке не дублируются.
- Если в процессе загрузки новой страницы контента отсутствовал интернет или произошла ошибка, то индикатор загрузки должен исчезнуть и пользователь должен увидеть стандартный Toast с сообщением «Проверьте подключение к интернету» или «Произошла ошибка».

**Comment by nataliakozhanova** [comment]
Судя по последнему пункту ТЗ, там должен быть свой обработчик ошибок. То есть, если весь ответ с сервера - картинки, если при постраничной загрузке - тосты, так?

**Comment by nataliakozhanova** [comment]
BUG: при постраничной загрузке (78 вакансий) на 2-й странице выключаю интернет.  Выскакивает тост "вы достигли конца списка", а должно выскакивать "нет интернета"

**Comment by AlexPanic** [comment]
> Судя по последнему пункту ТЗ, там должен быть свой обработчик ошибок. То есть, если весь ответ с сервера - картинки, если при постраничной загрузке - тосты, так?

Примерно так. Для первой и следующих страниц 2 разных стейта у SearchViewModel и соответственно 2 observe во фрагменте. И даже сообщения об ошибках со второй страницы другие. Все учтено.
