### ISSUE TITLE
Показ вакансии при переходе из избранного

### ISSUE THREAD

**Issue by AlexPanic** [AlexPanic/practicum-android-diploma#165]
Показ вакансии из базы (любым образом,
например
и в избранном и в поиске сейчас открывается VacancyDetailsFragment
в котором есть viewModel.getVacancy(vacancyId)
дальше в интеракторе не указать флаг
из какого репозитория брать: из сети или из Room
в зависимости от флага favorite)

Удаление протухшей вакансии из БД Избранного
Обновление вакансии в БД свежими данными из сети

**Comment by nataliakozhanova** [comment]
Не было реализовано в ПР - Удаление протухшей вакансии из БД Избранного (добавила)
Протестировала обновление вакансии: работает
Исправила багу с проверкой интернета
