### ISSUE TITLE
Загрузка справочников Hh: страны, регионы

### ISSUE THREAD

**Issue by AlexPanic** [AlexPanic/practicum-android-diploma#77]
функции для загрузки стран и регионов из HH

**Comment by nataliakozhanova** [comment]
Мы так и не поняли, зачем справочники для результатов серча нужны. Требуемый опыт и занятость - это уже в детейлз. Валюта приходит в результатах и в серче, там только RUR на ₽ поменять. Возможно, нужно уточнить еще раз задачу.

**Comment by AlexPanic** [comment]
Хорошо, задачу обдумаю и переставлю на себя

**Comment by nataliakozhanova** [comment]
Леша, уже неактуальная вроде задачка. Мы же их не грузим - просто запрашиваем, нет?

**Comment by nataliakozhanova** [comment]
В общем, она как бы входит в таску мою
